version: "3.10"

networks:
  base_proxy:
    external: true

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      - WEBSOCKET_ENABLED=true
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - DATABASE_MAX_CONNS=4
    volumes:
      - ./data:/data
    networks:
      - base_proxy
    labels:
      traefik.enable: true
      traefik.http.middlewares.vaultwarden-web-redirect.redirectscheme.scheme: https
      traefik.http.services.vaultwarden.loadbalancer.passhostheader: true
      traefik.http.services.vaultwarden.loadbalancer.server.port: 80
      # Web
      traefik.http.routers.vaultwarden-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.vaultwarden-insecure.entrypoints: web
      traefik.http.routers.vaultwarden-insecure.service: vaultwarden
      traefik.http.routers.vaultwarden-insecure.middlewares: vaultwarden-web-redirect
      # Websecure
      traefik.http.routers.vaultwarden.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.vaultwarden.entrypoints: websecure
      traefik.http.routers.vaultwarden.service: vaultwarden
      traefik.http.routers.vaultwarden.tls.certresolver: myresolver
