version: "3.10"

networks:
  base_proxy:
    external: true
  wikijs:


services:
  wikijs:
    image: ghcr.io/requarks/wiki:2.5.300
    depends_on:
      - wikijs-db
    environment:
      DB_TYPE: postgres
      DB_HOST: wikijs-db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: ${WIKI_JS_DB_PASS}
      DB_NAME: wiki
    restart: unless-stopped
    networks:
      - base_proxy
      - wikijs
    labels:
      traefik.enable: true
      traefik.http.middlewares.wikijs-web-redirect.redirectscheme.scheme: https
      traefik.http.services.wikijs.loadbalancer.passhostheader: true
      traefik.http.services.wikijs.loadbalancer.server.port: 3000
      # Web
      traefik.http.routers.wikijs-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.wikijs-insecure.entrypoints: web
      traefik.http.routers.wikijs-insecure.service: wikijs
      traefik.http.routers.wikijs-insecure.middlewares: wikijs-web-redirect
      # Websecure
      traefik.http.routers.wikijs.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.wikijs.entrypoints: websecure
      traefik.http.routers.wikijs.service: wikijs
      traefik.http.routers.wikijs.tls.certresolver: myresolver

  wikijs-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: ${WIKI_JS_DB_PASS}
      POSTGRES_USER: wikijs
    logging:
      driver: 'none'
    restart: unless-stopped
    networks:
      - wikijs
    volumes:
      - ${LOCAL_DATA_DIR}/postgres:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -d joplin
      interval: 5s
      timeout: 1s
      retries: 5
      start_period: 5s
