version: "3.10"

networks:
  base_proxy:
    external: true
  monica:


services:
  monica:
    image: monica:4.0.0
    depends_on:
      - monica-db
    environment:
      - APP_KEY=${MONICA_APP_KEY}
      - DB_HOST=monica-db
      - DB_USERNAME=usermonica
      - DB_PASSWORD=${MONICA_DB_PASS}
    volumes:
      - ${APP_DATA_DIR}/data:/var/www/html/storage
    restart: unless-stopped
    networks:
      - base_proxy
      - monica
    labels:
      traefik.enable: true
      traefik.http.middlewares.monica-web-redirect.redirectscheme.scheme: https
      traefik.http.services.monica.loadbalancer.passhostheader: true
      traefik.http.services.monica.loadbalancer.server.port: 80
      # Web
      traefik.http.routers.monica-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.monica-insecure.entrypoints: web
      traefik.http.routers.monica-insecure.service: monica
      traefik.http.routers.monica-insecure.middlewares: monica-web-redirect
      # Websecure
      traefik.http.routers.monica.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.monica.entrypoints: websecure
      traefik.http.routers.monica.service: monica
      traefik.http.routers.monica.tls.certresolver: myresolver

  monica-db:
    image: mariadb:10.8
    environment:
      - TZ=${TZ}
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MARIADB_DATABASE=monica
      - MARIADB_USER=usermonica
      - MARIADB_PASSWORD=${MONICA_DB_PASS}
    volumes:
      - ${APP_DATA_DIR}/mysql:/var/lib/mysql
    restart: unless-stopped
    networks:
      - monica
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute "SHOW DATABASES;"'
      interval: 5s
      timeout: 1s
      retries: 5
      start_period: 5s
