version: "3.10"

networks:
  base_proxy:
    external: true
  send:

services:
  send:
    image: registry.gitlab.com/timvisee/send:latest
    container_name: send
    restart: unless-stopped
    networks:
      - base_proxy
      - send
    volumes:
      - ./data/uploads:/uploads
    environment:
      - NODE_ENV=production
      # Networking
      - BASE_URL=https://${APP_DOMAIN}
      # Redis
      - REDIS_HOST=send-redis
      # Storage Limit
      - MAX_FILE_SIZE=2147483648
      # Storage path
      - FILE_DIR=/uploads
    depends_on:
      - send-redis
    labels:
      traefik.enable: true
      traefik.http.middlewares.send-web-redirect.redirectscheme.scheme: https
      traefik.http.services.send.loadbalancer.passhostheader: true
      traefik.http.services.send.loadbalancer.server.port: 3000
      # Web
      traefik.http.routers.send-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.send-insecure.entrypoints: web
      traefik.http.routers.send-insecure.service: send
      traefik.http.routers.send-insecure.middlewares: send-web-redirect
      # Websecure
      traefik.http.routers.send.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.send.entrypoints: websecure
      traefik.http.routers.send.service: send
      traefik.http.routers.send.tls.certresolver: myresolver

  send-redis:
    image: redis:alpine
    container_name: send-redis
    restart: unless-stopped
    volumes:
      - ${LOCAL_DATA_DIR}/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 30
    networks:
      - send
